name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: zhaoxlchn-deploy
        uses: zhaoxlchn/note@main
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_REPO: zhaoxlchn/note
          TARGET_BRANCH: website_html
          BUILD_SCRIPT: yarn && yarn docs:build
          BUILD_DIR: docs/.vitepress/dist
